language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install

script:
  - composer validate --strict
  - composer test
  - composer cs-ci
